### ISSUE TITLE
Problem to recover Owallet

### ISSUE THREAD

**Issue by rnick19** [ontio/OWallet#156]
Hi, 

I installed Owallet on my PC in december 2018 and staked some ONT on a node. Today I tried to open my wallet and the wallet is not there anymore.I had only one wallet created and it'S not there.  I have opened it last time in februrary and it was working fine. 

 I have the keystore.db file, my wallet address and also the password......but I don't have the pk WIF or pk 64HEX to recover the wallet. I was sure that I was able to recover the wallet with the keystore.db file but it seems that I need a keystone.dat file...that I don't have.

So I spoke with a guy name 'Panther' on your telegram and he sent et program (ont.exe) to recover my private key using the information inside my keystone.db file. 

I ran the program in my terminal (on pc) and filled with my correct information but I always get this error : 

**error:  decrypt private key error: cipher: message authentication failed**

​Here is the command I use in my terminal : 

Command to fill : ont.exe key adress salt password

My command:  ont.exe _XZFAY68ejkE2rxxxxxxxxxxxxxxxxxxxxJDNJG+2gGPsI+6ETwIib3Z2H3Olcpn9 AXcKWPggp3qVtxxxxxxxh4cHfKvv9eZca9 3VKqG/LhxxxxxxxxxxsWWwhFQ== Boxxxxx75!

I replaced some value with some xxxxxx here !!! There is a space between each parameters

After that I tried to create a new wallet and check if I was able to recover the pk with the info of the keystone.db from this new wallet  and  I got the same error....so I guess something is wrong in my command.

So I really don't know how to recover my wallet with my money now.....can you help me please?? If you need more information let me know. 

Also, this wallet was on PC and I would like to recover it on my mac when I succeed to recover it on my pc. Any different thing to do on mac when I will have my pk??

Thanks for your support.

**Comment by Sharla12** [comment]
HI,
I am having the same problem recovering my wallet.  Nothing seems to  work.  I had trouble retrieving my  transactions and and I was notified repeatedly that it was impossible to download them.  The transactions that were showing disappeared. 
I have the keystore file, the private key, the password, the public key.  Tried  importing the wallet and making a new wallet and it all fails.  I really need help, PLEASE

**Comment by MickWang** [comment]
1. Please make sure have backup the keystore.db file, the password.and other things.
2. Download and install the latest owallet.
3. Go to the setting page and set the path of directory where the keystore.db is.
4. Check if the wallets are normal.
Please do these things and tell me the results.

**Comment by Sharla12** [comment]
Mick Wang,It worked.Once I sent your message to my computer guru friend, he was able to restore the wallet.  I CAN NOT THANK YOU ENOUGH!  It was perfect and it fixed what has been wrong in the wallet for almost 2 weeks. It couldn't load any transactions so we tried everything and then since I had the info (I thought) to restore it, he deleted it.  THEN we were stuck until he saw and understood your instructions. 
Absolutely awesome and I'm so grateful.THANK YOU.Sharla12
    On Saturday, June 1, 2019, 4:26:57 AM CDT, MickWang <notifications@github.com> wrote:  
 
    
   - Please make sure have backup the keystore.db file, the password.and other things.
   - Download and install the latest owallet.
   - Go to the setting page and set the path of directory where the keystore.db is.
   - Check if the wallets are normal.   
Please do these things and tell me the results.

**Comment by MickWang** [comment]
You are welcome. :)
