### ISSUE TITLE
OWallet 0.9.24 - Not showing Unbound ONG

### ISSUE THREAD

**Issue by travek** [ontio/OWallet#244]
Hello team!
I upgraded to the lates version of OWallet - 0.9.24.
All my ONT are delegated.  When I was using older versions of OWallet I can see that the amount of Unbound ONG is increasing when observing my Stake Autorization page in the wallet. Right now the amount of Unbound ONG is 0 all the time
Please fix!

**Comment by robertd123066** [comment]
Same  here. ONG balance all messed up. Waited a few days to see if it was behind. Must be caught up now. Still wrong,,,oh well....

**Comment by travek** [comment]
@OWallet team,
any response on the issue ?

**Comment by robertd123066** [comment]
I get a common.txfailed when typing in my pass to get unbound gas from staking as well now

**Comment by MickWang** [comment]
Sorry for the delay.
we have new ong releasing model since Ontology 2.0 's upgrade,  July 07, 2020.
1. Holding ONT no longer increases unbound ONG now.
2. Staking no longer release unbound ong now. Older unbound ong will be sent together with the gas fee profit.

More details please refer to this doc: https://medium.com/ontologynetwork/continuing-to-refine-ontologys-governance-and-staking-economic-model-4c0c9cce1f51. Thanks.
