### ISSUE TITLE
Login with Ledger does not pick up same account as NEON wallet

### ISSUE THREAD

**Issue by friedhelmensch** [ontio/OWallet#28]
When logging in with Ledger you don´t get to use the same account as with the Neon wallet. 
This makes it impossible to access the ONT from the second airdrop.

expected:
Login with ledger (that also holds a NEO private key) opens account with airdropped ONT

actual:
random(?) new account is unlocked without any balance.

**Comment by Gettinfukinrich** [comment]
I sent ont coins to Neon yesterday by mistake .. I use a ledger on neon and I cant see the coins I sent in neon wallet but they did get there because the ont explorer shows that it was a success with the correct neon address..... I also have coins on onto 

How shall I get them all to Owallet or are some of them just lost forever ?

**Comment by friedhelmensch** [comment]
@Gettinfukinrich 
good news: your coins are not lost
bad news: it's not straightforward to access them.

you can wait until they implement the feature mentioned by @xiaomin49.
then you will be able to enter your 24 words (generated by the ledger) into OWallet and thus access the ONT again. 

**But you have to keep in mind that those 24 words (mnemonic passphrase) are usually not supposed to be exposed anywhere.** 

So my advice would be:
To be really save to not compromise funds on your ledger you should sent everything on it (even other coins beside NEO, e.g. Ether or Bitcoin or whatever you else you keep) 
to new addresses that you control before entering the mnemonic anywhere. The passphrase is then basically burned. You can reinitialise the ledger with a new passphrase afterwards and send your funds to the addresses of the reinitialised ledger.

**Comment by Gettinfukinrich** [comment]
Poop !!

And thank you much for the BitterSweet Info

**Comment by CriptiuGaeilge** [comment]
Mislaid ONT:
I transferred some ONT from an exchange to Owallet on my ledger nano S some weeks ago and all is good.
However I also transferred some ONT from NEON wallet on my ledger nano S many weeks ago to the same Owallet but cannot see them there!
I have since attained the knowledge that they cannot be seen as they are NEP5 ONT as opposed to the Mainnet ONT which is viewable.

In the meantime I have downloaded Owallet v0.8.8 and without ticking NEO address compatible I can open and see the Mainnet ONT containing the Owallet address just like before only containing the ONT I transferred via exchange.
Logging out and back in again, but this time ticking  NEO address compatible I can open the NEON wallet address but again a balance of 0 ONT.

How can I view the invisable NEP5 ONT (from NEON wallet address)  in which I sent to the Mainnet ONT (now on Owallet address)?

**Comment by MickWang** [comment]
You sent the NEP-5 ONT to the OWallet Mainnet ONT ledger address and OWallet does not support NEP-5 tokens, so you can not see NEP5 balance there.You can use O3 wallet and select the ONT compatible address mode.You will see the NEP5 balance there.

**Comment by Gettinfukinrich** [comment]
I do in deed see my Net 5 tokens in 03 but when I say too convert them to
ont tokens it says I'm using the wrong software on my ledger even though I
have the latest builds of Neo and ont on The Ledger and I try using them
both it still gives me the same message denied you're using the wrong key

So we're halfway there I can see them there's five thousand of those little
Beauties there but it will not let me do anything with them I've tried
sending them 2 o wallet gives me the same message will not allow me to send
them and will not allow me to convert them so poop and I'm running out of
time

**Comment by MickWang** [comment]
Do you want to convert or transfer your nep-5 tokens with O3 wallet but failed, right? Is the nep-5 tokens on the ONT address of your ledger? Please make sure you have updated the NEO app on your ledger with Ledger Live. Then you may need to connect with O3 and select the ONT compatible mode, and try again. If still not success, you may need to ask the help of O3 team.

**Comment by MickWang** [comment]
OWallet supports NEO compatible address for ledger wallet now.
O3 wallet supports ONT compatible address for ledger wallet now.
