### ISSUE TITLE
Invalid ONT ID

### ISSUE THREAD

**Issue by jonatanblockchain** [ontio/OWallet#66]
I've created two ONT IDs and looks like succefully (I can see them on the dashboard), but I can not find it in explorer.ont.io also when I try to use the option Node Stake I get an error "Invalid ONT ID"

**Comment by MickWang** [comment]
Which version did you use to create the ONT ID. There is a bug about creating ONT ID in the old version and it was fixed in the latest version. The ONT ID you see on the dashboard is actually not created successfully. Please create the new one again. About the ONT ID created failed, now there is no option to remove it. Will add this function later.
Thanks.
